name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: aws s3 cp index.html s3://uf-gha-demo/index.html --acl public-read
    #   run: aws s3 rm s3://uf-gha-demo --recursive 
    #   run: aws s3 rb s3://uf-gha-demo

